export const menuApi = [
      {
        id: "offer1",
        name: "Big Mac Meal Deal",
        description: "Big Mac, Medium Fries & Medium Drink",
        price: 5.99,
        discountPrice: 4.99,
        calories: 850,
        category: "Burgers",
        subCategory: "Meal Deals",
        image: "/restaurantsMenu/burgers/b11.jpg",
      },
      {
        id: "offer2",
        name: "2 Cheeseburger Meal",
        description: "2 Cheeseburgers, Small Fries & Small Drink",
        price: 4.49,
        discountPrice: 3.99,
        calories: 780,
        image: "/restaurantsMenu/fries/image (3).jpeg",
      },
      {
        id: "offer3",
        name: "Chicken Nuggets Deal",
        description: "6pc Nuggets, Fries & Drink",
        price: 4.99,
        discountPrice: 4.49,
        calories: 720,
        image: "/restaurantsMenu/nuggets/image (14).jpeg",
      },
      {
        id: "offer4",
        name: "Family Combo",
        description: "2 Big Macs, 2 Fries, 2 Drinks",
        price: 12.99,
        discountPrice: 11.49,
        calories: 1600,
        image: "/restaurantsMenu/salads/image (6).jpeg",
      },
      {
        id: "offer5",
        name: "Lunch Saver",
        description: "Cheeseburger, Small Fries & Drink",
        price: 3.99,
        discountPrice: 3.49,
        calories: 690,
        image: "/restaurantsMenu/fish/image (12).jpeg",
      },
      {
        id: "offer6",
        name: "Double Patty Deal",
        description: "Double Cheeseburger with Fries",
        price: 5.49,
        discountPrice: 4.99,
        calories: 880,
        image: "/restaurantsMenu/fish/image (7).jpeg",
      },
      {
        id: "offer7",
        name: "Weekend Value Pack",
        description: "3 Burgers, 3 Fries, 3 Drinks",
        price: 14.99,
        discountPrice: 12.99,
        calories: 2100,
        image: "/restaurantsMenu/sauces/image (4).jpeg",
      },
      {
        id: "offer8",
        name: "Happy Hour Meal",
        description: "Burger + Apple Pie + Drink",
        price: 5.25,
        discountPrice: 4.75,
        calories: 770,
        image: "/restaurantsMenu/orbit/images (6).jpeg",
      },
      {
        id: "offer9",
        name: "Veggie Delight Combo",
        description: "Veggie Burger, Fries & Drink",
        price: 4.99,
        discountPrice: 4.49,
        calories: 650,
        image: "/restaurantsMenu/hot_drinks/image (9).jpeg",
      },
      {
        id: "offer10",
        name: "Mini Feast Box",
        description: "Mini Burgers x2, Small Fries, Drink",
        price: 5.59,
        discountPrice: 4.99,
        calories: 740,
        image: "/restaurantsMenu/shakes/image (9).jpeg",
      },
      {
        id: "burger1",
        name: "Big Mac",
        description: "The one with two beef patties and special sauce",
        price: 3.99,
        calories: 550,
        image: "/restaurantsMenu/burgers/b11.jpg",
      },
      {
        id: "burger2",
        name: "Quarter Pounder with Cheese",
        description: "Quarter pound beef patty with cheese",
        price: 4.29,
        calories: 520,
        image: "/restaurantsMenu/burgers/b12.jpg",
      },
      {
        id: "burger3",
        name: "Cheeseburger",
        description: "Classic beef patty with cheese and pickles",
        price: 1.99,
        calories: 300,
        image: "/restaurantsMenu/burgers/image (8).jpeg",
      },
      {
        id: "burger4",
        name: "Double Cheeseburger",
        description: "Two beef patties with cheese",
        price: 2.89,
        calories: 450,
        image: "/restaurantsMenu/burgers/image (9).jpeg",
      },
      {
        id: "burger5",
        name: "McChicken",
        description: "Crispy chicken patty with mayo and lettuce",
        price: 3.49,
        calories: 430,
        image: "/restaurantsMenu/burgers/image (10).jpeg",
      },
      {
        id: "burger6",
        name: "Spicy McChicken",
        description: "Spicy version of classic McChicken",
        price: 3.59,
        calories: 440,
        image: "/restaurantsMenu/burgers/image (11).jpeg",
      },
      {
        id: "burger7",
        name: "Veggie Burger",
        description: "Grilled veggie patty with lettuce and tomato",
        price: 3.29,
        calories: 400,
        image: "/restaurantsMenu/burgers/image (12).jpeg",
      },
      {
        id: "burger8",
        name: "Fish Fillet",
        description: "Crispy fish patty with tartar sauce",
        price: 3.89,
        calories: 390,
        image: "/restaurantsMenu/burgers/image (13).jpeg",
      },
      {
        id: "burger9",
        name: "Bacon Cheeseburger",
        description: "Beef patty, bacon and cheese",
        price: 4.19,
        calories: 560,
        image: "/restaurantsMenu/burgers/images (4).jpeg",
      },
      {
        id: "burger10",
        name: "BBQ Beef Burger",
        description: "Beef patty with BBQ sauce and onions",
        price: 4.49,
        calories: 590,
        image: "/restaurantsMenu/burgers/images (5).jpeg",
      },
      {
        id: "fries1",
        name: "Medium Fries",
        description: "World famous golden fries",
        price: 1.89,
        calories: 340,
        image: "/restaurantsMenu/fries/image (3).jpeg",
      },
      {
        id: "fries2",
        name: "Large Fries",
        description: "More of our golden fries",
        price: 2.19,
        calories: 510,
        image: "/restaurantsMenu/fries/image (4).jpeg",
      },
      {
        id: "fries3",
        name: "Small Fries",
        description: "Perfect snack-size fries",
        price: 1.49,
        calories: 230,
        image: "/restaurantsMenu/fries/image (5).jpeg",
      },
      {
        id: "fries4",
        name: "Cheesy Fries",
        description: "Fries topped with melted cheese",
        price: 2.79,
        calories: 450,
        image: "/restaurantsMenu/fries/image (6).jpeg",
      },
      {
        id: "fries5",
        name: "Curly Fries",
        description: "Crispy, curly fries",
        price: 2.29,
        calories: 390,
        image: "/restaurantsMenu/fries/image (7).jpeg",
      },
      {
        id: "fries6",
        name: "Loaded Fries",
        description: "Topped with cheese, bacon and jalapeños",
        price: 3.49,
        calories: 550,
        image: "/restaurantsMenu/fries/image (8).jpeg",
      },
      {
        id: "fries7",
        name: "Sweet Potato Fries",
        description: "Sweet and crispy fries",
        price: 2.39,
        calories: 300,
        image: "/restaurantsMenu/fries/image (9).jpeg",
      },
      {
        id: "fries8",
        name: "Garlic Fries",
        description: "Fries with garlic seasoning",
        price: 2.59,
        calories: 370,
        image: "/restaurantsMenu/fries/image (10).jpeg",
      },
      {
        id: "fries9",
        name: "Waffle Fries",
        description: "Criss-cross shaped fries",
        price: 2.49,
        calories: 400,
        image: "/restaurantsMenu/fries/image (11).jpeg",
      },
      {
        id: "fries10",
        name: "Fries with Gravy",
        description: "Fries served with warm gravy",
        price: 2.89,
        calories: 430,
        image: "/restaurantsMenu/fries/image (12).jpeg",
      },
      {
        id: "snack1",
        name: "Chicken McNuggets (6pc)",
        description: "Bite-sized chicken pieces",
        price: 3.29,
        calories: 250,
        image: "/restaurantsMenu/nuggets/image (14).jpeg",
      },
      {
        id: "snack2",
        name: "Apple Slices",
        description: "Fresh sliced apples",
        price: 1.19,
        calories: 15,
        image: "/restaurantsMenu/nuggets/image (4).jpeg",
      },
      {
        id: "snack3",
        name: "Mozzarella Sticks",
        description: "Fried cheesy sticks",
        price: 2.99,
        calories: 320,
        image: "/restaurantsMenu/nuggets/image (5).jpeg",
      },
      {
        id: "snack4",
        name: "Chicken Snack Wrap",
        description: "Mini wrap with crispy chicken",
        price: 2.59,
        calories: 270,
        image: "/restaurantsMenu/nuggets/image (6).jpeg",
      },
      {
        id: "snack5",
        name: "Hash Browns",
        description: "Crispy breakfast hash browns",
        price: 1.49,
        calories: 150,
        image: "/restaurantsMenu/nuggets/image (13).jpeg",
      },
      {
        id: "snack6",
        name: "Side Corn",
        description: "Steamed sweet corn",
        price: 1.89,
        calories: 80,
        image: "/restaurantsMenu/nuggets/image (8).jpeg",
      },
      {
        id: "snack7",
        name: "Fruit Bag",
        description: "Mixed fresh fruits",
        price: 1.29,
        calories: 90,
        image: "/restaurantsMenu/nuggets/image (9).jpeg",
      },
      {
        id: "snack8",
        name: "Choco Pie",
        description: "Chocolate covered pie snack",
        price: 1.79,
        calories: 200,
        image: "/restaurantsMenu/nuggets/image (10).jpeg",
      },
      {
        id: "snack9",
        name: "Yogurt Cup",
        description: "Creamy yogurt with fruit",
        price: 1.59,
        calories: 120,
        image: "/restaurantsMenu/nuggets/image (11).jpeg",
      },
      {
        id: "snack10",
        name: "Mini Pancakes",
        description: "6 fluffy mini pancakes",
        price: 2.49,
        calories: 280,
        image: "/restaurantsMenu/nuggets/image (12).jpeg",
      },
      {
        id: "salad1",
        name: "Side Salad",
        description: "Fresh garden salad",
        price: 2.49,
        calories: 50,
        image: "/restaurantsMenu/salads/image (6).jpeg",
      },
      {
        id: "salad2",
        name: "Grilled Chicken Salad",
        description: "Salad with grilled chicken",
        price: 5.29,
        calories: 220,
        image: "/restaurantsMenu/salads/image (7).jpeg",
      },
      {
        id: "salad3",
        name: "Caesar Salad",
        description: "Classic Caesar with croutons",
        price: 4.99,
        calories: 190,
        image: "/restaurantsMenu/salads/image (8).jpeg",
      },
      {
        id: "salad4",
        name: "Greek Salad",
        description: "Feta cheese, olives, and veggies",
        price: 5.19,
        calories: 210,
        image: "/restaurantsMenu/salads/image (9).jpeg",
      },
      {
        id: "salad5",
        name: "Spicy Chicken Salad",
        description: "Salad with spicy grilled chicken",
        price: 5.59,
        calories: 250,
        image: "/restaurantsMenu/salads/image (10).jpeg",
      },
      {
        id: "salad6",
        name: "Veggie Delight Salad",
        description: "All-vegetable salad mix",
        price: 4.29,
        calories: 90,
        image: "/restaurantsMenu/salads/image (11).jpeg",
      },
      {
        id: "salad7",
        name: "Avocado Salad",
        description: "Sliced avocado with greens",
        price: 5.49,
        calories: 180,
        image: "/restaurantsMenu/salads/image (12).jpeg",
      },
      {
        id: "salad8",
        name: "Chicken Bacon Ranch",
        description: "Salad with grilled chicken and bacon",
        price: 5.79,
        calories: 260,
        image: "/restaurantsMenu/salads/image (13).jpeg",
      },
      {
        id: "salad9",
        name: "Southwest Chicken Salad",
        description: "Bold flavors, corn & beans",
        price: 5.99,
        calories: 290,
        image: "/restaurantsMenu/salads/image (14).jpeg",
      },
      {
        id: "salad10",
        name: "Tuna Salad",
        description: "Salad with tuna and veggies",
        price: 5.49,
        calories: 240,
        image: "/restaurantsMenu/salads/image (15).jpeg",
      },
      {
        id: "drink1",
        name: "Coca-Cola (Medium)",
        description: "Classic Coca-Cola",
        price: 1.79,
        calories: 210,
        image: "/restaurantsMenu/shakes/image (5).jpeg",
      },
      {
        id: "drink2",
        name: "Iced Latte",
        description: "Cold coffee drink",
        price: 2.49,
        calories: 120,
        image: "/restaurantsMenu/shakes/image (6).jpeg",
      },
      {
        id: "drink3",
        name: "Sprite (Large)",
        description: "Lemon-lime flavored soda",
        price: 1.99,
        calories: 200,
        image: "/restaurantsMenu/shakes/image (7).jpeg",
      },
      {
        id: "drink4",
        name: "Fanta Orange",
        description: "Fruity orange soda",
        price: 1.89,
        calories: 190,
        image: "/restaurantsMenu/shakes/image (8).jpeg",
      },
      {
        id: "drink5",
        name: "Iced Tea",
        description: "Refreshing sweet tea",
        price: 1.69,
        calories: 140,
        image: "/restaurantsMenu/shakes/image (9).jpeg",
      },
      {
        id: "drink6",
        name: "Cold Brew Coffee",
        description: "Slow-steeped cold coffee",
        price: 2.79,
        calories: 10,
        image: "/restaurantsMenu/shakes/image (10).jpeg",
      },
      {
        id: "drink7",
        name: "Vanilla Shake",
        description: "Cold vanilla-flavored shake",
        price: 2.99,
        calories: 410,
        image: "/restaurantsMenu/shakes/image (11).jpeg",
      },
      {
        id: "drink8",
        name: "Chocolate Shake",
        description: "Thick chocolate shake",
        price: 2.99,
        calories: 430,
        image: "/restaurantsMenu/shakes/image (12).jpeg",
      },
      {
        id: "drink9",
        name: "Bottled Water",
        description: "Pure spring water",
        price: 1.29,
        calories: 0,
        image: "/restaurantsMenu/shakes/image (13).jpeg",
      },
      {
        id: "drink10",
        name: "Mango Smoothie",
        description: "Blended mango drink",
        price: 2.59,
        calories: 160,
        image: "/restaurantsMenu/shakes/images (14).jpeg",
      },
      {
        id: "happy1",
        name: "Happy Meal Hamburger",
        description: "Hamburger, fries, drink & toy",
        price: 3.49,
        calories: 480,
        image: "/restaurantsMenu/fish/image (4).jpeg",
      },
      {
        id: "happy2",
        name: "Happy Meal Chicken Nuggets",
        description: "4pc nuggets, fries, drink & toy",
        price: 3.69,
        calories: 420,
        image: "/restaurantsMenu/fish/image (5).jpeg",
      },
      {
        id: "happy3",
        name: "Happy Meal Cheeseburger",
        description: "Cheeseburger meal with toy",
        price: 3.89,
        calories: 500,
        image: "/restaurantsMenu/fish/image (7).jpeg",
      },
      {
        id: "happy4",
        name: "Happy Meal Fish Bites",
        description: "Fish bites, fries, drink & toy",
        price: 3.99,
        calories: 410,
        image: "/restaurantsMenu/fish/image (9).jpeg",
      },
      {
        id: "happy5",
        name: "Happy Meal Veggie Wrap",
        description: "Wrap with veggies & toy",
        price: 3.59,
        calories: 390,
        image: "/restaurantsMenu/fish/image (10).jpeg",
      },
      {
        id: "happy6",
        name: "Happy Meal Mini Pizza",
        description: "Mini pizza, fries, drink & toy",
        price: 4.29,
        calories: 460,
        image: "/restaurantsMenu/fish/image (12).jpeg",
      },
      {
        id: "happy7",
        name: "Happy Meal Grilled Cheese",
        description: "Grilled cheese, fries & toy",
        price: 3.49,
        calories: 400,
        image: "/restaurantsMenu/fish/images (2).jpeg",
      },
      {
        id: "happy8",
        name: "Happy Meal Hot Dog",
        description: "Hot dog meal with toy",
        price: 3.99,
        calories: 430,
        image: "/restaurantsMenu/fish/images (9).jpeg",
      },
      {
        id: "happy9",
        name: "Happy Meal Egg Sandwich",
        description: "Egg sandwich & toy",
        price: 3.79,
        calories: 390,
        image: "/restaurantsMenu/fish/images (10).jpeg",
      },
      {
        id: "happy10",
        name: "Happy Meal Pancake",
        description: "Mini pancake stack & toy",
        price: 3.59,
        calories: 450,
        image: "/restaurantsMenu/fish/images (11).jpeg",
      },
      {
        id: "dessert1",
        name: "McFlurry (M&M)",
        description: "Creamy vanilla soft serve with M&M candies",
        price: 2.19,
        calories: 340,
        image: "/restaurantsMenu/desserts/image (4).jpeg",
      },
      {
        id: "dessert2",
        name: "Apple Pie",
        description: "Warm apple pie",
        price: 1.29,
        calories: 240,
        image: "/restaurantsMenu/desserts/image (5).jpeg",
      },
      {
        id: "dessert3",
        name: "Chocolate Sundae",
        description: "Vanilla ice cream with chocolate topping",
        price: 1.59,
        calories: 330,
        image: "/restaurantsMenu/desserts/image (6).jpeg",
      },
      {
        id: "dessert4",
        name: "Strawberry Sundae",
        description: "Strawberry topping over ice cream",
        price: 1.59,
        calories: 320,
        image: "/restaurantsMenu/desserts/image (7).jpeg",
      },
      {
        id: "dessert5",
        name: "Caramel Sundae",
        description: "Caramel drizzle on vanilla ice cream",
        price: 1.59,
        calories: 310,
        image: "/restaurantsMenu/desserts/image (8).jpeg",
      },
      {
        id: "dessert6",
        name: "Chocolate Chip Cookie",
        description: "Fresh baked cookie",
        price: 0.99,
        calories: 160,
        image: "/restaurantsMenu/desserts/image (9).jpeg",
      },
      {
        id: "dessert7",
        name: "Brownie",
        description: "Rich chocolate brownie",
        price: 1.79,
        calories: 280,
        image: "/restaurantsMenu/desserts/image (10).jpeg",
      },
      {
        id: "dessert8",
        name: "Vanilla Cone",
        description: "Classic vanilla soft serve cone",
        price: 1.19,
        calories: 200,
        image: "/restaurantsMenu/desserts/image (11).jpeg",
      },
      {
        id: "dessert9",
        name: "Milkshake (Strawberry)",
        description: "Strawberry flavored shake",
        price: 2.99,
        calories: 400,
        image: "/restaurantsMenu/desserts/image (12).jpeg",
      },
      {
        id: "dessert10",
        name: "Donut",
        description: "Glazed donut",
        price: 1.49,
        calories: 270,
        image: "/restaurantsMenu/desserts/image (13).jpeg",
      },
      {
        id: "hot1",
        name: "Premium Roast Coffee",
        description: "Freshly brewed coffee",
        price: 1.39,
        calories: 5,
        image: "/restaurantsMenu/hot_drinks/image (5).jpeg",
      },
      {
        id: "hot2",
        name: "Hot Chocolate",
        description: "Rich chocolate drink",
        price: 1.89,
        calories: 370,
        image: "/restaurantsMenu/hot_drinks/image (6).jpeg",
      },
      {
        id: "hot3",
        name: "Cappuccino",
        description: "Espresso with milk foam",
        price: 2.49,
        calories: 90,
        image: "/restaurantsMenu/hot_drinks/image (7).jpeg",
      },
      {
        id: "hot4",
        name: "Espresso Shot",
        description: "Strong espresso coffee",
        price: 1.19,
        calories: 2,
        image: "/restaurantsMenu/hot_drinks/image (8).jpeg",
      },
      {
        id: "hot5",
        name: "Latte",
        description: "Creamy hot milk coffee",
        price: 2.79,
        calories: 110,
        image: "/restaurantsMenu/hot_drinks/image (9).jpeg",
      },
      {
        id: "hot6",
        name: "Green Tea",
        description: "Hot brewed green tea",
        price: 1.59,
        calories: 0,
        image: "/restaurantsMenu/hot_drinks/image (15).jpeg",
      },
      {
        id: "hot7",
        name: "Black Tea",
        description: "Plain hot black tea",
        price: 1.49,
        calories: 0,
        image: "/restaurantsMenu/hot_drinks/image (11).jpeg",
      },
      {
        id: "hot8",
        name: "Chai Latte",
        description: "Spiced tea with milk",
        price: 2.59,
        calories: 180,
        image: "/restaurantsMenu/hot_drinks/image (12).jpeg",
      },
      {
        id: "hot9",
        name: "Americano",
        description: "Espresso with hot water",
        price: 1.99,
        calories: 10,
        image: "/restaurantsMenu/hot_drinks/image (13).jpeg",
      },
      {
        id: "hot10",
        name: "Mocha",
        description: "Chocolate flavored coffee",
        price: 2.89,
        calories: 200,
        image: "/restaurantsMenu/hot_drinks/image (14).jpeg",
      },
      {
        id: "sauce1",
        name: "BBQ Sauce",
        description: "Smoky barbecue sauce",
        price: 0.3,
        calories: 45,
        image: "/restaurantsMenu/sauces/image (4).jpeg",
      },
      {
        id: "sauce2",
        name: "Sweet & Sour",
        description: "Tangy dipping sauce",
        price: 0.3,
        calories: 50,
        image: "/restaurantsMenu/sauces/image (4).jpeg",
      },
      {
        id: "sauce3",
        name: "Ranch",
        description: "Creamy ranch dressing",
        price: 0.3,
        calories: 60,
        image: "/restaurantsMenu/sauces/image (5).jpeg",
      },
      {
        id: "sauce4",
        name: "Honey Mustard",
        description: "Sweet mustard sauce",
        price: 0.3,
        calories: 70,
        image: "/restaurantsMenu/sauces/image (6).jpeg",
      },
      {
        id: "sauce5",
        name: "Buffalo Sauce",
        description: "Spicy buffalo-style sauce",
        price: 0.3,
        calories: 40,
        image: "/restaurantsMenu/sauces/image (7).jpeg",
      },
      {
        id: "sauce6",
        name: "Ketchup",
        description: "Classic tomato ketchup",
        price: 0.2,
        calories: 20,
        image: "/restaurantsMenu/sauces/image (8).jpeg",
      },
      {
        id: "sauce7",
        name: "Mayonnaise",
        description: "Creamy mayo",
        price: 0.2,
        calories: 90,
        image: "/restaurantsMenu/sauces/image (9).jpeg",
      },
      {
        id: "sauce8",
        name: "Tartar Sauce",
        description: "Mayo-based with pickles",
        price: 0.3,
        calories: 80,
        image: "/restaurantsMenu/sauces/image (10).jpeg",
      },
      {
        id: "sauce9",
        name: "Chili Sauce",
        description: "Hot chili condiment",
        price: 0.3,
        calories: 30,
        image: "/restaurantsMenu/sauces/image (11).jpeg",
      },
      {
        id: "sauce10",
        name: "Garlic Sauce",
        description: "Garlicky white sauce",
        price: 0.3,
        calories: 60,
        image: "/restaurantsMenu/sauces/image (12).jpeg",
      },
      {
        id: "orbit1",
        name: "Orbit Chewing Gum",
        description: "Spearmint flavor chewing gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/image (5).jpeg",
      },
      {
        id: "orbit2",
        name: "Orbit Wintergreen",
        description: "Wintergreen flavor chewing gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/image (12).jpeg",
      },
      {
        id: "orbit3",
        name: "Orbit Peppermint",
        description: "Peppermint gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/image (13).jpeg",
      },
      {
        id: "orbit4",
        name: "Orbit Strawberry",
        description: "Strawberry flavored gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/image (16).jpeg",
      },
      {
        id: "orbit5",
        name: "Orbit Watermelon",
        description: "Watermelon flavored gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/image (17).jpeg",
      },
      {
        id: "orbit6",
        name: "Orbit Citrus",
        description: "Citrus blend gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/images (4).jpeg",
      },
      {
        id: "orbit7",
        name: "Orbit Bubblegum",
        description: "Classic bubblegum flavor",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/images (6).jpeg",
      },
      {
        id: "orbit8",
        name: "Orbit Tropical",
        description: "Tropical fruit flavored gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/images (13).jpeg",
      },
      {
        id: "orbit9",
        name: "Orbit Vanilla Mint",
        description: "Vanilla mint flavored gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/images (15).jpeg",
      },
      {
        id: "orbit10",
        name: "Orbit Lemon Ice",
        description: "Cool lemon icy gum",
        price: 0.5,
        calories: 5,
        image: "/restaurantsMenu/orbit/images (16).jpeg",
      },
];
